name: TestCoverageCommit
description: Commit coverage report
inputs:
  github_token:
    description: Value of secrets.GITHUB_TOKEN
    required: true
  source_branch_coverage_file:
    description: Path to file for generated new report file for source branch
    required: true
  target_branch_coverage_file:
    description: Path to file for existing report be committed from 'source_branch_coverage_file'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
      shell: bash

    - name: Copy Coverage Report
      run: cp ${{ inputs.source_branch_coverage_file }} ${{ inputs.target_branch_coverage_file }}
      shell: bash

    - name: Stage Coverage Report
      run: git add ${{ inputs.target_branch_coverage_file }}
      shell: bash

    - name: Commit Coverage Report
      run: git commit -m "${{ inputs.target_branch_coverage_file }} > automated commit"
      shell: bash

    - name: Push Changes
      run: git push
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
