name: Build

on:
  # Run workflow when PRs are merged into one of branch
  push:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/publish.yml'

  # Run workflow for all PRs where target branch is one of
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/publish.yml'

  # for test purpose only
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x] # 18.x

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        uses: ./.github/actions/test

      - name: Test Coverage
        if: success() || failure()
        uses: ./.github/actions/test_coverage
        with:
          coverage_file: ./coverage/report.json

      - name: List, audit, fix outdated dependencies and build again
        run: |
          npm list --outdated
          npm audit || true  # ignore failures
          npm audit fix || true
          npm list --outdated
          npm run build
