name: Build

on:
  # Run workflow when PRs are merged into one of branch
  push:
    branches: [main]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/Pull_Request_Template.md'
      - '.github/workflows/publish.yml'
      - 'README.md'
      - 'LICENSE'

  # Run workflow for all PRs where target branch is one of
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/Pull_Request_Template.md'
      - '.github/workflows/publish.yml'
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: List, audit, fix outdated dependencies and build again
        run: |
          npm list --outdated
          npm audit || true  # ignore failures
          npm audit fix || true
          npm list --outdated
          npm run build

      - name: Test
        uses: ./.github/actions/test
        with:
          report_name_suffix: ${{ matrix.node-version }}

      - name: Test Coverage
        if: ${{ github.event_name == 'pull_request' && always() }}
        uses: ./.github/actions/test_coverage
        with:
          report_name_suffix: ${{ matrix.node-version }}
          coverage_file: ./coverage/new_report.json
