name: Build

on:
  # Run workflow when PRs are merged into one of branch
  push:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/publish.yml'

  # Run workflow for all PRs where target branch is one of
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/publish.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH_COVERAGE_FILE: ./coverage/new_report.json

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x] #18.x,

    steps:
      - name: Set Target Branch Coverage File
        run: |
          echo "TARGET_BRANCH_COVERAGE_FILE=./coverage/report_${{ matrix.node-version }}.json" >> $GITHUB_ENV
          echo "event_name: ${{ github.event_name }}"

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        uses: ./.github/actions/test
        with:
          report_name_suffix: ${{ matrix.node-version }}

      - name: Test Coverage
        if: success() || failure()
        uses: ./.github/actions/test_coverage
        with:
          report_name_suffix: ${{ matrix.node-version }}
          source_branch_coverage_file: ${{ env.SOURCE_BRANCH_COVERAGE_FILE }}
          target_branch_coverage_file: ${{ env.TARGET_BRANCH_COVERAGE_FILE }}

      - name: Test Coverage Commit
        if: success() || failure()
        #${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/test_coverage_commit
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_ref: ${{ github.head_ref }}
          source_branch_coverage_file: ${{ env.SOURCE_BRANCH_COVERAGE_FILE }}
          target_branch_coverage_file: ${{ env.TARGET_BRANCH_COVERAGE_FILE }}

      - name: List, audit, fix outdated dependencies and build again
        run: |
          npm list --outdated
          npm audit || true  # ignore failures
          npm audit fix || true
          npm list --outdated
          npm run build
