name: Build

on:
  # Run workflow when PRs are merged into one of branch
  push:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/publish.yml'

  # Run workflow for all PRs where target branch is one of
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - '.github/workflows/publish.yml'

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH_COVERAGE_FILE: ./coverage/new_report.json

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Set Target Branch Coverage File
        run: |
          echo "TARGET_BRANCH_COVERAGE_FILE=./coverage/report_${{ matrix.node-version }}.json" >> $GITHUB_ENV
          echo "event_name: ${{ github.event_name }}"

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        uses: ./.github/actions/test
        with:
          report_name_suffix: ${{ matrix.node-version }}

      - name: Test Coverage
        if: success() || failure()
        uses: ./.github/actions/test_coverage
        with:
          report_name_suffix: ${{ matrix.node-version }}
          source_branch_coverage_file: ${{ env.SOURCE_BRANCH_COVERAGE_FILE }}
          target_branch_coverage_file: ${{ env.TARGET_BRANCH_COVERAGE_FILE }}

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v4.3.6
        with:
          name: test-coverage-report-${{ matrix.node-version }}
          path: ${{ env.TARGET_BRANCH_COVERAGE_FILE }}

      - name: List, audit, fix outdated dependencies and build again
        run: |
          npm list --outdated
          npm audit || true  # ignore failures
          npm audit fix || true
          npm list --outdated
          npm run build

  commit_test_coverage_reports:
    name: Commit Test Coverage Reports
    needs: [build]
    if: ${{ github.event_name == 'pull_request' && always() }}
    runs-on: ubuntu-latest
    env:
      COVERAGE_FILE_18.x: ./coverage/report_18.x.json
      COVERAGE_FILE_20.x: ./coverage/report_20.x.json

    steps:
      - uses: actions/checkout@v4

      - name: Download Test Coverage Report (18.x)
        uses: actions/download-artifact@v4.1.8
        with:
          name: test-coverage-report-18.x
          path: ${{ env.COVERAGE_FILE_18 }}

      - name: Download Test Coverage Report (20.x)
        uses: actions/download-artifact@v4.1.8
        with:
          name: test-coverage-report-20.x
          path: ${{ env.COVERAGE_FILE_20 }}

      - name: Commit Test Coverage Reports
        uses: ./.github/actions/commit
        with:
          comment: Test Coverage Reports
          changes_paths: ${{ env.COVERAGE_FILE_18 }} ${{ env.COVERAGE_FILE_20 }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
